---
- name: Configure High Availability Squid Proxy Farm
  hosts: all
  become: yes
  serial: 1

  roles:
    - common      # Kernel tuning, UFW, and OS updates
    - monitoring  # Prometheus Node Exporter
    - squid       # The optimized 5MB-aware Squid config